# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import collections
from collections import deque

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.beginWord = "cat"
        self.endWord = "fog"
        self.wordList = ["fog", "dog", "dot", "bat", "cog", "bot", "bog"]
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BeginLabel = QtWidgets.QLabel(self.centralwidget)
        self.BeginLabel.setEnabled(True)
        self.BeginLabel.setGeometry(QtCore.QRect(30, 30, 441, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BeginLabel.setFont(font)
        self.BeginLabel.setObjectName("BeginLabel")
        self.EndLabel = QtWidgets.QLabel(self.centralwidget)
        self.EndLabel.setEnabled(True)
        self.EndLabel.setGeometry(QtCore.QRect(30, 110, 441, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.EndLabel.setFont(font)
        self.EndLabel.setObjectName("EndLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 230, 93, 28))
        self.pushButton.clicked.connect(self.result)
        self.pushButton.setObjectName("pushButton")
        
        self.lbl_hasil = QtWidgets.QLabel(self.centralwidget)
        self.lbl_hasil.move(200, 500)
        
        self.Answer = QtWidgets.QLineEdit(self.centralwidget)
        self.Answer.setGeometry(QtCore.QRect(30, 230, 113, 22))
        self.Answer.setText("")
        self.Answer.setObjectName("Answer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def result(self):
        # lbl_hasil = QtWidgets.QLabel(win)
        ans = self.ladderLength(self.beginWord, self.endWord, self.wordList)
        # print(self.Answer.text())
        if self.Answer.text() == str(ans):
            # lbl_hasil = QtWidgets.QLabel(win)
            self.lbl_hasil.setText("betul")
            # lbl_hasil.move(200, 200)
            # print('correct')
        else:
            # lbl_hasil = QtWidgets.QLabel(win)
            self.lbl_hasil.setText("wrong")
            # lbl_hasil.move(200, 200)
            # print('wrong')
        self.lbl_hasil.adjustSize()

    def ladderLength(self, beginWord: str, endWord: str, wordList) -> int:
        if endWord not in wordList:
            return 0
        
        nei = collections.defaultdict(list)
        wordList.append(beginWord)
        for word in wordList:
            for j in range(len(word)):
                pattern = word[:j] + "*" + word[j + 1:]
                nei[pattern].append(word)
                
        visit = set([beginWord])
        q = deque([beginWord])
        res = 1
        while q:
            for i in range(len(q)):
                word = q.popleft()
                if word == endWord:
                    return res
                for j in range(len(word)):
                    pattern = word[:j] + "*" + word[j + 1:]
                    for neiWord in nei[pattern]:
                        if neiWord in nei[pattern]:
                            visit.add(neiWord)
                            q.append(neiWord)
            res += 1
        return 0

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BeginLabel.setText(_translate("MainWindow", "Begin Word : "+self.beginWord))
        self.EndLabel.setText(_translate("MainWindow", "End Word : "+self.endWord))
        self.pushButton.setText(_translate("MainWindow", "Check"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
